name: messenger
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  auto_route: ^8.2.0
  auto_route_generator: ^8.0.0
  flutter_slidable: ^3.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.0.0
  auto_route_generator: ^8.0.0

flutter:
  generate: true
#  l10n:
#    arb-dir:lib/l10n
#    output-localization-file: app_localizations.dart
#    output-class: AppLocalizations
#    output-dir: lib/generated

  uses-material-design: true

  assets:
   - assets/icons/
   - assets/images/
   - assets/layout/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
